<a href="https://colab.research.google.com/github/nedokormysh/OpenEdu_HSE_INTRML/blob/week4/HW04_sgd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание по неделе 4

Как было рассказано на лекции, стохастический градиентый спуск сходится быстрее, чем полный, хотя и менее стабильно. В этом задании вам предлагается реализовать стохастический градиентный спуск и сравнить его с точным вычислением весов линейной модели по скорости работы и значению метрики качества.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
import pandas as pd
import warnings
from sklearn.metrics import mean_absolute_percentage_error


np.random.seed(0)

warnings.filterwarnings('ignore')
%matplotlib inline

### Задание 0

Реализуйте класс ```LinearRegressionSGD``` c обучением и и применением линейной регрессии, построенной с помощью стохастического градиентного спуска, с заданным интерфейсом.

In [ ]:
from sklearn.base import BaseEstimator

class LinearRegressionSGD(BaseEstimator):
    def __init__(self, epsilon=1e-4, max_steps=100, w0=None, alpha=1e-4):
        """
        epsilon: разница для нормы изменения весов 
        max_steps: максимальное количество шагов в градиентном спуске
        w0: np.array (d,) - начальные веса
        alpha: шаг обучения
        """
        self.epsilon = epsilon
        self.max_steps = max_steps
        self.w0 = w0
        self.alpha = alpha
        self.w = None
        self.w_history = []
    
    def fit(self, X, y):
        # """
        # X: np.array (l, d)
        # y: np.array (l)
        # ---
        # output: self
        # """
        # ## На каждом шаге градиентного спуска веса необходимо добавлять в w_history
        
        # return self

        """
        X: np.array (l, d)
        y: np.array (l)
        ---
        output: self
        """
        # print(X.shape)
        l, d = X.shape

        
        if self.w0 is None:
          self.w0 = np.zeros(d)
        
        self.w = self.w0

        i = 0

        for step in range(self.max_steps):
          i += 1
          self.w_history.append(self.w)

          train_ind = np.random.randint(l)

          w_new = self.w - self.alpha * self.calc_gradient(X[train_ind], y[train_ind])

          if (np.linalg.norm(w_new - self.w) < self.epsilon):
            print(i)
            break
          
          self.w = w_new

          # print(self.w)

        return self
    
    def predict(self, X):
        # """
        # X: np.array (l, d)
        # ---
        # output: np.array (l)
        # """
        
        # return 
        
        if self.w is None:
            raise Exception('Not trained yet')

        return np.dot(X, self.w)
    
    def calc_gradient(self, X, y):
        # """
        # X: np.array (l, d)
        # y: np.array (l)
        # ---
        # output: np.array (d)
        # """

        # return gradient

        """
        X: np.array (l, d)
        y: np.array (l)
        ---
        output: np.array (d)
        """
        

        # l, d = X.shape
        # gradient = []

        # for j in range(d):
        #     dQ = 0
        #     for i in range(l):
        #         dQ += (2 / l) * X[i][j] * (np.dot(X[i], self.w) - y[i])
        #     gradient.append(dQ)
        # l, d = X.shape

        # return (2/l) * np.dot(X.T,(np.dot(X, self.w) - y))
        return 2 * np.dot(X.T,(np.dot(X, self.w) - y))

        # return np.array(gradient)

Проверять работу мы будем на имеющемся в sklearn наборе данных boston: в нём нужно по информации о доме предсказать его стоимость.

In [ ]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

data = load_boston()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

X_train, X_test, y_train, y_test = train_test_split(np.array(X), y, test_size=0.3, random_state=10)

### Задание 1

Метрикой качества в нашей задаче будет MAPE - Mean Absolute Percentage Error. Реализуйте её с заданным интефейсом и вычислите 
```MAPE(y_test, y_0)```, где ```y_0 = (mean(y_test), mean(y_test), ...)```

In [ ]:
def MAPE(y_true, y_pred):
    """
        y_true: np.array (l)
        y_pred: np.array (l)
        ---
        output: float [0, +inf)
    """
    return 

#### тестирование mape

In [ ]:
y_true_tst_1 = [3, -0.5, 2, 7]
y_pred_tst_1 = [2.5, 0.0, 2, 8]

In [ ]:
y_true_tst_2 = [1, 2, 1, 2, 3, -0.5]
y_pred_tst_2 = [1, 1, 1, 1, 1, 2]

In [ ]:
mean_absolute_percentage_error(y_true_tst_1, y_pred_tst_1)

0.3273809523809524

In [ ]:
mean_absolute_percentage_error(y_true_tst_2, y_pred_tst_2)

1.111111111111111

In [ ]:
def mape(y_true, y_pred):
  y_true, y_pred = np.array(y_true), np.array(y_pred)

  return np.mean(np.abs((y_pred - y_true) / y_true))

In [ ]:
mape(y_true_tst_1, y_pred_tst_1)

0.3273809523809524

In [ ]:
mape(y_true_tst_2, y_pred_tst_2)

0.3333333333333333

In [ ]:
# def mape_2(y_true, y_pred):
#   Q = 0
  
#   for i in range(1, len(y_true)):
#     Q += abs((y_true[i] - y_pred[i]) / y_true[i])
     
#   Q = 100 * Q / len(y_true)
#   return Q /100

In [ ]:
# mape_2(y_true_tst_1, y_pred_tst_1)

In [ ]:
# mape_2(y_true_tst_2, y_pred_tst_2)

#### Решение задачи

In [ ]:
# y_0 = y_test.mean()
y_0 = []
for i in range(len(y_test)):
  y_0.append(y_test.mean())
# print(y_test)
# print(y_0)
# print(len(y_test))
# print(len(y_0))
mape(y_test, y_0) * 100

37.41588297684096

In [ ]:
mean_absolute_percentage_error(y_test, y_0)

0.37415882976840964

### Задание 2 

Обучите ```LinearRegressionSGD``` с базовыми параметрами на тренировочном наборе данных (```X_train```, ```y_train```), сделайте предсказание на тестовых данных ```X_test```, записав результат в переменную ```y_pred_sgd```  и вычислите ошибку MAPE.

In [ ]:
def prep(X, y):
  n_features = X.shape[1]
  # print(n_features)
  n_objects = X.shape[0]
  # print(n_objects)
  num_steps = 2

  np.random.seed(1)
  w_0 = np.random.uniform(-2, 2, (n_features))

  return w_0

In [ ]:
w_prep_0 = prep(X_train, y_train)
w_prep_0

array([-0.33191198,  0.88129797, -1.9995425 , -0.79066971, -1.41297644,
       -1.63064562, -1.25495915, -0.61775709, -0.4129301 ,  0.15526694,
       -0.32322194,  0.740878  , -1.182191  ])

In [ ]:
X_train

array([[1.20830e-01, 0.00000e+00, 2.89000e+00, ..., 1.80000e+01,
        3.96900e+02, 4.21000e+00],
       [3.40060e-01, 0.00000e+00, 2.18900e+01, ..., 2.12000e+01,
        3.95040e+02, 1.26000e+01],
       [1.50234e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.49480e+02, 2.49100e+01],
       ...,
       [2.37857e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.70730e+02, 1.33400e+01],
       [1.69020e-01, 0.00000e+00, 2.56500e+01, ..., 1.91000e+01,
        3.85020e+02, 1.48100e+01],
       [7.61620e-01, 2.00000e+01, 3.97000e+00, ..., 1.30000e+01,
        3.92400e+02, 1.04500e+01]])

In [ ]:
X_train[:, 12].shape

(354,)

In [ ]:
model_sgd = LinearRegressionSGD(w0=w_prep_0, alpha=1e-10)
model_sgd.fit(X_train, y_train)
y_pred_sgd = model_sgd.predict(X_test)
print(mape(y_test, y_pred_sgd) * 100)

1
840.845420547911


In [ ]:
from sklearn.linear_model import SGDRegressor

SGDReg = SGDRegressor(max_iter=100000, tol=1e-3)
SGDReg.fit(X_train, y_train)
y_pred_SGDreg = model_sgd.predict(X_test)
print(mape(y_test, y_pred_SGDreg))

8.40845420547911


### Задание 3

Вычислите веса по точной формуле, используя ```X_train``` и ```y_train```; предскажите с их помощью целевую переменную на ```X_test```, записав результат в переменную ```y_pred_lr``` и вычислите ошибку MAPE.

In [ ]:
## y_pred_lr = ...

MAPE(y_test, y_pred_lr)

In [ ]:
# a, b = X_test.shape
# w_0 = np.random.uniform(-2, 2, (b))
# lr = LinearRegressionSGD(w0=w_0)
# lr.fit(X_train, y_train)
# y_pred_lr = lr.predict(X_test)
# print(MAPE(y_test, y_pred_lr))

In [ ]:
# w_precise = np.dot(np.dot(X_train.T, X_train)**(-1), np.dot(X_train.T, y_train)) 

$w=(X^TX)^{-1}X^Ty$

In [ ]:
w_analog = np.dot(inv(np.dot(X_train.T, X_train)), np.dot(X_train.T, y_train))
w_analog

array([-1.45793025e-01,  6.40188977e-02, -2.47416777e-02,  1.56887412e+00,
       -1.91523982e+00,  5.43085567e+00,  3.45547728e-03, -1.03110328e+00,
        1.87024628e-01, -9.29477195e-03, -3.24703939e-01,  1.86182543e-02,
       -4.53776475e-01])

In [ ]:
y_prep_lr = np.dot(X_test, w_analog)
y_prep_lr

array([30.34582503, 31.24831457, 29.33356798, 25.70451414, 18.43204509,
       16.48618502, 35.69910601, 15.90418493, 23.63985816, 38.25773946,
       21.55802752, 30.36224556, 25.98671119, 33.21276813, 33.36841304,
       42.21297385, 25.16527368, 20.57976463, 23.63152818, 22.55567074,
       31.38553297, 19.43922022, 24.43556204, 25.44882623, 32.60657343,
       20.75677237, 19.10530651, 18.1383063 , 37.97017025, -3.77744325,
       31.40499062, 31.71710679, 27.29073678, 23.35369156, 21.46554664,
       19.57328508,  4.38487118, 35.85071127, 25.92959349, 26.51603955,
       35.40069675, 28.56642584, 19.78626086, 30.20029954, 17.47905259,
       29.05908187, 21.24288777, 21.33445123, 37.7901613 , 17.64092896,
       22.13250964, 21.09540115, 22.48517405, 35.72804596, 28.54967663,
       34.30925333, 19.62833036, 21.60815278, 15.60640098, 27.13515994,
       22.0697755 , 22.8481547 , 41.4247949 , 44.75961712, 29.00249034,
       19.02222133, 22.89362104,  0.99784897, 29.8269934 , 33.90

In [ ]:
y_test

array([28.4, 31.1, 23.5, 26.6, 19.6, 14.3, 50. , 14.3, 20.7, 37.6, 20.4,
       27.5, 36.2, 32. , 33.1, 48.8, 24.6, 26.4, 23.2, 17. , 41.3, 14.9,
       18.5, 25. , 36.4, 19.5, 27.1, 14.9, 46. , 17.9, 30.3, 31.6, 23.1,
       24.7, 16.7, 18.3,  8.4, 37.3, 22.1, 22. , 46.7, 30.1, 12.1, 29.1,
       16.6, 23.9, 19.9, 21.4, 45.4, 15.6, 22.7, 12.5, 24.3, 43.8, 22. ,
       33.8, 19.3, 22.6, 16.1, 15. , 19.6, 21.2, 50. , 50. , 29.4, 17.8,
       22.8,  8.8, 32.5, 42.8, 12.6, 28.6, 19.1, 50. , 27.5, 23.7, 50. ,
        7.2, 18.7, 37. , 22.9, 22.9, 17.1, 22. , 23.6, 23.9, 27.1, 29. ,
       22.2,  7. , 20.7, 18.5, 21.6, 23. , 16. , 15. , 23.9, 24.4, 22.6,
       19.8, 22.2, 18.6, 19.7, 23.1, 13.5, 21.2, 23.1, 13.6, 22.8, 18.2,
       13.1, 23.2, 22.8, 25.1, 18.9, 10.9, 19.3, 17.4, 15.6, 20.6, 50. ,
       32.7, 21.8, 13.4, 16.6, 23.6, 11. , 23.8, 23.1, 33.2, 28.2,  8.5,
       32.4, 29.6, 17.1, 24.2, 26.4, 33.2, 10.5,  8.8, 28. , 10.5, 15.4,
       15.3, 10.4, 15.7, 43.1, 24.7, 21. , 19.4, 10

In [ ]:
mape(y_test, y_prep_lr)

0.18953134816376593

## Бонусное задание по неделе 4

До этого вы релизовывали модели, в которых не было штрафа за величину весов ```w```. Как было рассказано ранее в лекциях, это может привести к неустойчивости модели и переобучению. Чтобы избежать этих эффектов, предлагается добавить к оптимизируемому функционалу L2-норму весов; таким образом, будем решать задачу гребневой регрессии, Ridge:

$$ \frac{1}{l}(Xw-y)^T(Xw-y) +\gamma||w||_2 \rightarrow \min_{w}. $$

### Задание 11
Реализуйте обучение такой модели в матричном виде (смотрите дополнительные материалы к этой неделе) с помощью стохастического градиентного спуска. Класс должен совпадать по набору реализованных функций с ```LinearRegressionVectorized```, разница будет лишь в параметре $\gamma$, отвечающем за степень регуляризации. 

In [ ]:
class RidgeSGD(BaseEstimator):
    def __init__(self, epsilon=1e-4, max_steps=1000, w0=None, alpha=1e-2, gamma=0):
        """
        epsilon: разница для нормы изменения весов 
        max_steps: максимальное количество шагов в градиентном спуске
        w0: np.array (d,) - начальные веса
        alpha: шаг обучения
        gamma: коэффициент регуляризации
        """
        self.epsilon = epsilon
        self.max_steps = max_steps
        self.w0 = w0
        self.alpha = alpha
        self.gamma = gamma
        self.w = None
        self.w_history = []
    
    def fit(self, X, y):
        """
        X: np.array (l, d)
        y: np.array (l)
        ---
        output: self
        """
        return self
    
    def predict(self, X):
        """
        X: np.array (l, d)
        ---
        output: np.array (l)
        """
        pass

    
    def calc_gradient(self, X, y):
        """
        X: np.array (l, d)
        y: np.array (l)
        ---
        output: np.array (d)
        """
        pass

Так же, как и в основном задании, обучите модель с базовыми параметрами на тренировочных данных и сделайте прогноз y_pred_ridge. Выведите значение MAPE(y_test, y_pred_ridge).