<a href="https://colab.research.google.com/github/nedokormysh/OpenEdu_HSE_INTRML/blob/week3/Numpy_Screencast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

На данном семинаре мы изучим библиотеку [numpy](https://numpy.org/). numpy - очень удобная и быстрая библиотека, которая предсоставляет возможность выполнять различные операции над массивами и матрицами. В машинном обучении многие операции работы с данными могут быть представлены, как операции из линейной алгебры. Именно поэтому знание этой библиотеки очень важно.

Для начала познакомимся с базовым объектом в numpy - numpy.ndarray

In [ ]:
import numpy as np

In [ ]:
array = np.array([1, 2, 4])

Код выше создал вектор длины 3. Теперь мы можем выполнять различные арифметические операции над этим вектором.

In [ ]:
array

array([1, 2, 4])

In [ ]:
array * 2

array([2, 4, 8])

In [ ]:
array + 5

array([6, 7, 9])

In [ ]:
np.mean(array)

2.3333333333333335

In [ ]:
np.sum(array)

7

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
X = np.random.normal(size=(3, 3))

In [ ]:
X

array([[-0.97207539, -1.06404618,  0.22788302],
       [ 0.55305239,  0.23002691, -0.41094772],
       [-0.51508366,  2.60427071,  1.64788214]])

In [ ]:
X.dot(X)

array([[ 0.23907847,  1.38304293,  0.59127224],
       [-0.19871923, -1.60578002, -0.6456912 ],
       [ 1.09220112,  5.43865632,  1.52791761]])

In [ ]:
X @ X

array([[ 0.23907847,  1.38304293,  0.59127224],
       [-0.19871923, -1.60578002, -0.6456912 ],
       [ 1.09220112,  5.43865632,  1.52791761]])

In [ ]:
np.linalg.det(X)

-0.3090807551125686

strings

In [ ]:
X[[0, 2]]

array([[-0.97207539, -1.06404618,  0.22788302],
       [-0.51508366,  2.60427071,  1.64788214]])

columns

In [ ]:
X[:, [0, 2]]

array([[-0.97207539,  0.22788302],
       [ 0.55305239, -0.41094772],
       [-0.51508366,  1.64788214]])

In [ ]:
X[0, 1]

-1.0640461832748493

Пусть хотим взять только те строки, где сумма элементов больше нуля. Для этого нужно посчитать сумму в строках, т.е. сумму вдоль столбцовой оси.

In [ ]:
np.sum(X, axis=1)

array([-1.80823856,  0.37213157,  3.73706918])

In [ ]:
np.sum(X, axis=1) > 0

array([False,  True,  True])

In [ ]:
X[np.sum(X, axis=1) > 0]

array([[ 0.55305239,  0.23002691, -0.41094772],
       [-0.51508366,  2.60427071,  1.64788214]])

In [ ]:
X[:, np.sum(X, axis=1) > 0]

array([[-1.06404618,  0.22788302],
       [ 0.23002691, -0.41094772],
       [ 2.60427071,  1.64788214]])

Нампай написан на си, поэтому он в разы быстрее, чем листы в питоне.

In [ ]:
%%time
1 + 1

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs


2

In [ ]:
a = np.arange(100000)

In [ ]:
b = np.random.normal(size=100000)

In [ ]:
%%time

np.sum(a*b)

CPU times: user 1.93 ms, sys: 1.06 ms, total: 3 ms
Wall time: 1.93 ms


-13449133.125088636

In [ ]:
%%time
sum_prod = 0

for i in range(100000):
  sum_prod += a[i] * b[i]

CPU times: user 277 ms, sys: 867 µs, total: 278 ms
Wall time: 281 ms


Мы можем выполнять поэлементные операции на массивах одинаковой длины.

In [ ]:
array_2 = np.array([9, 2, 0])

In [ ]:
array + array_2

array([10,  4,  4])

In [ ]:
array * array_2

array([9, 4, 0])

С массивами можно работать как с листами и вытаскивать оттуда элементы по индексу. В тоже время, можно использовать индексацию по условию и вытаскивать элементы с помощью булевой маски.

In [ ]:
array[1]

2

In [ ]:
array[1:]

array([2, 4])

In [ ]:
print(array_2 > 0)
print(array[array_2 > 0])

[ True  True False]
[1 2]


В numpy можно работать не только с векторами, но и с матрицами и массивами большей размерности. Давайте создадим матрицу, которая состоит из одних единиц.

In [ ]:
matrix = np.ones((2, 4))

In [ ]:
matrix.shape

(2, 4)

In [ ]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Над матрицами мы можем выполнять все те же операции, что и над векторами. Также мы можем считать среднее, сумму как по всем элементам, так и вдоль осей.

In [ ]:
np.sum(matrix)

8.0

In [ ]:
np.sum(matrix, axis=1)

array([4., 4.])

Можем создавать случайный матрицы.

In [ ]:
random_matrix = np.random.normal(size=(2, 2))
random_matrix

array([[-0.15202536,  0.04675802],
       [ 0.60686314, -0.45267678]])

Можем умножать матрицы и выполнять различные операции линейной алгебры.

In [ ]:
matrix.T @ random_matrix

array([[ 0.45483778, -0.40591875],
       [ 0.45483778, -0.40591875],
       [ 0.45483778, -0.40591875],
       [ 0.45483778, -0.40591875]])

In [ ]:
np.linalg.det(random_matrix)

0.040442629348055266

In [ ]:
np.linalg.matrix_rank(random_matrix)

2